#!/usr/bin/env bash
# Bring up the replica set from nothing: secrets, TLS material, cluster, roles.
#
# Everything this generates is local and gitignored. No credential is committed,
# and none is printed except the application connection string, which you need
# in order to use the thing.
#
# Idempotent: safe to re-run. Existing keys and certs are kept; rs.initiate and
# user creation both no-op when already done.
set -euo pipefail

# Git Bash rewrites arguments that look like absolute paths, which turns
# openssl's -subj "/CN=..." into "C:/Program Files/Git/CN=...". Harmless on a
# real Linux shell, essential on Windows.
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'

cd "$(dirname "$0")"
ENV_FILE=../.env

# The env file lives at the repo root because the application reads it too, and
# compose only looks next to the compose file unless told otherwise.
# ENCRYPTED=1 swaps the Community image for Percona Server for MongoDB, which
# supports encryption at rest. See docker-compose.encrypted.yml.
# A freshly installed Docker on Linux leaves the user outside the docker group
# until they log out and back in. The runner detects that and sets DOCKER="sudo
# docker" so the run continues instead of stopping for a re-login.
COMPOSE="${DOCKER:-docker} compose --env-file $ENV_FILE -f docker-compose.yml"
if [ "${ENCRYPTED:-0}" = "1" ]; then
  COMPOSE="$COMPOSE -f docker-compose.encrypted.yml"
fi

# --- credentials -----------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  echo "==> generating $ENV_FILE"
  gen() { openssl rand -base64 33 | tr -d '\n/+=' | cut -c1-32; }
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/bootstrap.sh. Local development only. Never commit.
MONGO_ROOT_USER=facts_root
MONGO_ROOT_PASSWORD=$(gen)
MONGO_APP_USER=facts_app
MONGO_APP_PASSWORD=$(gen)
MONGO_READONLY_USER=facts_ro
MONGO_READONLY_PASSWORD=$(gen)
MONGO_DB=factlayer
EOF
  chmod 600 "$ENV_FILE"
fi
set -a; . "$ENV_FILE"; set +a

# --- internal auth keyfile -------------------------------------------------
# Shared secret the replica set members authenticate to each other with.
# Enabling it also turns on RBAC for clients, which is the point.
mkdir -p secrets tls
if [ ! -f secrets/keyfile ]; then
  echo "==> generating replica set keyfile"
  openssl rand -base64 756 > secrets/keyfile
  chmod 400 secrets/keyfile
fi

# Data-at-rest key, used only by the Percona variant. Generated unconditionally
# so switching to it does not require a second setup step.
if [ ! -f secrets/encryption.key ]; then
  echo "==> generating encryption-at-rest key"
  openssl rand -base64 32 > secrets/encryption.key
  chmod 400 secrets/encryption.key
fi

# --- TLS -------------------------------------------------------------------
# Self-signed CA plus one server certificate carrying every name a client or a
# peer might dial: the container names, localhost, and 127.0.0.1.
if [ ! -f tls/server.pem ]; then
  echo "==> generating self-signed CA and server certificate"
  openssl req -x509 -newkey rsa:4096 -days 825 -nodes \
    -keyout tls/ca.key -out tls/ca.crt \
    -subj "/CN=superjoin-facts-ca/O=superjoin-assignment" 2>/dev/null

  openssl req -newkey rsa:4096 -nodes \
    -keyout tls/server.key -out tls/server.csr \
    -subj "/CN=mongo1/O=superjoin-assignment" 2>/dev/null

  cat > tls/server.ext <<'EOF'
subjectAltName = DNS:mongo1, DNS:mongo2, DNS:mongo3, DNS:host.docker.internal, DNS:localhost, IP:127.0.0.1
extendedKeyUsage = serverAuth, clientAuth
EOF

  openssl x509 -req -in tls/server.csr -CA tls/ca.crt -CAkey tls/ca.key \
    -CAcreateserial -out tls/server.crt -days 825 \
    -extfile tls/server.ext 2>/dev/null

  cat tls/server.key tls/server.crt > tls/server.pem
  chmod 400 tls/server.pem tls/ca.key tls/server.key
  rm -f tls/server.csr tls/server.ext
fi

# Every mongosh call goes through here: TLS against the self-signed CA, plus
# root credentials. Enabling the keyfile also enables authorization, so even
# replSetInitiate has to authenticate.
msh() {
  $COMPOSE exec -T \
    -e MONGO_APP_USER -e MONGO_APP_PASSWORD \
    -e MONGO_READONLY_USER -e MONGO_READONLY_PASSWORD -e MONGO_DB \
    mongo1 mongosh --quiet --tls \
      --tlsCAFile /tls-ca.crt --tlsAllowInvalidHostnames \
      -u "$MONGO_ROOT_USER" -p "$MONGO_ROOT_PASSWORD" \
      --authenticationDatabase admin "$@"
}

# --- cluster ---------------------------------------------------------------
echo "==> starting three mongod nodes"
$COMPOSE up -d

echo "==> waiting for mongo1 to accept authenticated connections"
ready=""
for _ in $(seq 1 60); do
  if msh --eval 'db.adminCommand("ping")' >/dev/null 2>&1; then ready=yes; break; fi
  sleep 2
done

# Without this the script pressed on to rs.initiate and reported "container is
# restarting", which is a symptom of the failure rather than the failure. mongod
# has already written the real reason to its own log by this point.
if [ -z "$ready" ]; then
  echo
  echo "mongo1 never became ready. Its last lines:" >&2
  ${DOCKER:-docker} logs --tail 25 facts-mongo1 2>&1 | sed 's/^/    /' >&2
  echo >&2
  echo "If that mentions a keyfile or certificate it could not read, the volumes" >&2
  echo "are from an older attempt - clear them and re-run:" >&2
  echo "    $COMPOSE down -v" >&2
  exit 1
fi

# Members are named by their container hostnames, which is what lets each node
# recognise itself and reach its peers. The cost is that a driver on the host
# cannot follow the set's own topology - it would be told to dial "mongo2",
# which does not resolve outside the compose network - so the application
# connects with directConnection. See README "Storage" for the consequence and
# the one-line fix.
echo "==> initiating replica set"
msh --eval '
  const already = (() => { try { rs.status(); return true; } catch (e) { return false; } })();
  if (already) { print("already initiated"); }
  else {
    rs.initiate({_id: "rs0", members: [
      {_id: 0, host: "mongo1:27017", priority: 2},
      {_id: 1, host: "mongo2:27017", priority: 1},
      {_id: 2, host: "mongo3:27017", priority: 1}
    ]});
    print("initiated");
  }'

echo "==> waiting for a primary"
for _ in $(seq 1 60); do
  msh --eval 'quit(db.hello().isWritablePrimary ? 0 : 1)' >/dev/null 2>&1 && break
  sleep 2
done

echo "==> applying roles and users"
msh < mongo-init/roles.js

echo "==> replica set members"
msh --eval 'rs.status().members.forEach(m => print("   " + m.name + "  " + m.stateStr))'

# Git Bash reports /a/superjoin-proj/..., which the Python driver cannot open on
# Windows. cygpath -m gives A:/superjoin-proj/..., valid in a URI and openable.
CA_PATH="$(pwd)/tls/ca.crt"
if command -v cygpath >/dev/null 2>&1; then
  CA_PATH="$(cygpath -m "$CA_PATH")"
fi
URI="mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@localhost:27017/${MONGO_DB}?directConnection=true&tls=true&tlsCAFile=${CA_PATH}&tlsAllowInvalidHostnames=true&authSource=${MONGO_DB}"

if ! grep -q '^MONGO_URI=' "$ENV_FILE"; then
  printf 'MONGO_URI=%s\n' "$URI" >> "$ENV_FILE"
  echo "==> wrote MONGO_URI to $ENV_FILE"
fi

echo
echo "Replica set rs0 is up on 27017/27018/27019. TLS required, RBAC on."
echo "The application connection string is in $ENV_FILE (gitignored)."
